// ── Analyst service (SPEC §8) ───────────────────────────
//
// The single entry point for the analyst feature. It runs on the server only:
// the API route calls `askAnalyst`, and the browser never touches a provider,
// a credential or the dataset directly.
//
// Guarantees enforced here:
//   * the query is read-only and bounded (length, characters, no instructions)
//   * retrieval selects only the summaries the question needs
//   * imported notes are treated as untrusted DATA, never as instructions
//   * no health value is ever written to a log
//   * a configured provider is named, and every answer states which provider and
//     model produced it — that provenance is not a permission gate
//   * a model reply is parsed and validated before it becomes an answer, and its
//     numeric claims are audited against the selected context
//   * a misconfigured or failing provider says so — it never falls back to demo
//     output and canned text is never presented as a live model response

import { REFERENCE_KEY } from '../adapters/dataset';
import type { UnitSystem } from '../prefs';
import { getMetric } from '../metrics/registry';
import { selectHandler, selectHandlerStrict } from './handlers';
import { SUPPORTED_PROMPTS } from './prompts';
import { AnalysisNotAvailable, GENERAL_HANDLER_ID, retrieve, retrieveGeneral } from './retrieval';
import { AnalystProviderError, createProvider, DEMO_LABEL } from './provider';
import { readAnalystConfig, type AnalystConfig } from './config';
import { checkGrounding, parseAnalystReply } from './validate';
import { boundedHistory } from './memory';
import type {
  AnalystAnswer,
  AnalystGrounding,
  AnalystRequest,
  AnalystResponse,
  AnalystStatus,
  RetrievalBundle,
} from './types';

export const QUERY_MAX_CHARS = 400;
export const NOTES_MAX_CHARS = 1000;

export const EDUCATIONAL_NOTICE =
  'Educational information about your own recorded data. Not medical advice, not a diagnosis, and not a substitute for a clinician.';

const DEMO_NOTICE =
  'Demo analyst — no AI provider is configured, so every answer below is computed from your dataset by deterministic handlers with pattern-matching question routing, not generated by a language model.';

const NO_GROUNDING: AnalystGrounding = { checked: 0, unmatched: [] };

// ── Input validation ────────────────────────────────────

export interface ValidatedQuery {
  ok: boolean;
  query: string;
  reason: string | null;
}

/** Read-only, bounded validation of the incoming question. */
export function validateQuery(raw: unknown): ValidatedQuery {
  if (typeof raw !== 'string') return { ok: false, query: '', reason: 'The question must be text.' };
  // Strip control characters before anything else.
  const cleaned = raw.replace(/[\u0000-\u001F\u007F]/g, ' ').trim();
  if (cleaned.length === 0) return { ok: false, query: '', reason: 'Enter a question to ask.' };
  if (cleaned.length > QUERY_MAX_CHARS) {
    return {
      ok: false,
      query: cleaned.slice(0, QUERY_MAX_CHARS),
      reason: `Questions are limited to ${QUERY_MAX_CHARS} characters; this one was ${cleaned.length}.`,
    };
  }
  return { ok: true, query: cleaned, reason: null };
}

export interface SanitizedNotes {
  received: boolean;
  characters: number;
  /** The notes are kept as opaque text. They are never parsed or executed. */
  text: string;
  truncated: boolean;
  note: string;
}

/**
 * Imported notes are untrusted data. They are length-capped, stripped of
 * control characters and kept as opaque text: nothing in them is interpreted as
 * an instruction, and they are never used to compute an answer.
 */
export function sanitizeUntrustedNotes(raw: unknown): SanitizedNotes {
  if (typeof raw !== 'string' || raw.trim().length === 0) {
    return { received: false, characters: 0, text: '', truncated: false, note: 'No imported notes were attached to this question.' };
  }
  const cleaned = raw.replace(/[\u0000-\u001F\u007F]/g, ' ').trim();
  const truncated = cleaned.length > NOTES_MAX_CHARS;
  const text = truncated ? cleaned.slice(0, NOTES_MAX_CHARS) : cleaned;
  return {
    received: true,
    characters: text.length,
    text,
    truncated,
    note: `Notes are treated as untrusted data: ${text.length} characters received${truncated ? ` (truncated from ${cleaned.length})` : ''}. They are never followed as instructions and are not used to compute any figure in this answer.`,
  };
}

// ── Service ─────────────────────────────────────────────

/** Label shown in the UI: never a key, never a plain "remote". */
function labelFor(config: AnalystConfig): string {
  if (config.misconfiguredReason) return `${config.providerDisplayName} (misconfigured)`;
  return config.provider === 'demo' ? DEMO_LABEL : config.providerDisplayName;
}

function baseResponse(config: AnalystConfig, status: AnalystStatus, fields: Partial<AnalystResponse> = {}): AnalystResponse {
  return {
    status,
    label: labelFor(config),
    provider: config.provider,
    providerLabel: config.providerDisplayName,
    providerDisplayName: config.providerDisplayName,
    model: config.provider === 'demo' ? null : config.model,
    providerConfigured: config.provider !== 'demo' && config.misconfiguredReason === null,
    systemPromptSource: config.provider === 'demo' ? 'built-in' : config.systemPromptSource,
    misconfiguredReason: config.misconfiguredReason,
    handlerId: 'none',
    answer: null,
    message: null,
    suggested: SUPPORTED_PROMPTS,
    notice: config.provider === 'demo' ? DEMO_NOTICE : EDUCATIONAL_NOTICE,
    retrieval: { recordsRead: 0, note: 'No dataset context was selected.', metrics: [] },
    grounding: NO_GROUNDING,
    untrustedNotes: { received: false, characters: 0, note: 'No imported notes were attached to this question.' },
    ...fields,
  };
}

function retrievalSummary(bundle: RetrievalBundle | null): AnalystResponse['retrieval'] {
  if (!bundle) return { recordsRead: 0, note: 'No dataset context was selected.', metrics: [] };
  return {
    recordsRead: bundle.recordsRead,
    note: bundle.note,
    metrics: bundle.summaries.map(s => ({
      metricId: s.metricId,
      window: `${s.lengthLabel} (${s.window.startKey} → ${s.window.endKey})`,
      observations: s.counts.evaluated,
    })),
  };
}

/**
 * Ask the analyst a question.
 *
 * With no provider configured this is deterministic, offline and read-only. With
 * a provider configured the same request goes to that provider — a configured
 * provider is used directly — and the reply is validated before it is returned.
 *
 * `deps.env` exists so the provider configuration can be injected in tests; in
 * production it defaults to the server process environment.
 */
export async function askAnalyst(
  request: AnalystRequest,
  deps: { env?: NodeJS.ProcessEnv } = {}
): Promise<AnalystResponse> {
  const config = readAnalystConfig(deps.env ?? process.env);
  const validated = validateQuery(request?.query);
  const notes = sanitizeUntrustedNotes(request?.notes);
  const notesEcho = { received: notes.received, characters: notes.characters, note: notes.note };
  const base = (status: AnalystStatus, fields: Partial<AnalystResponse> = {}) =>
    baseResponse(config, status, { untrustedNotes: notesEcho, ...fields });

  if (!validated.ok) {
    return base('error', { message: validated.reason });
  }

  // A provider is named but cannot be used: state why, compute nothing, send nothing.
  if (config.misconfiguredReason) {
    return base('misconfigured', {
      message: `${config.misconfiguredReason} No request was sent and no answer was computed.`,
    });
  }

  const isDemo = config.provider === 'demo';
  // Routing differs by path on purpose.
  //
  // The demo analyst answers its supported questions by pattern matching, and a
  // bare mention of sleep still routes to the shortest sleep window: there, the
  // patterns *are* the supported list.
  //
  // A configured provider answers the question the user actually asked, so a
  // handler bundle is used only when the question genuinely matches that
  // handler's canonical question. Otherwise the bounded general selection is
  // used and the model answers from it — the alternative is a multi-topic
  // question ("caffeine…, and how does it relate to my sleep?") being answered
  // from one metric, with the other half unanswerable.
  const matched = isDemo ? selectHandler(validated.query) : selectHandlerStrict(validated.query);

  // The demo analyst still answers only its supported questions, unchanged.
  if (isDemo && !matched) {
    return base('unsupported', {
      message: `The demo analyst matches questions by pattern, so it cannot route "${validated.query}". Nothing was computed or sent. Try one of the supported questions below.`,
    });
  }

  // Retrieval selects only what this question needs. A free-form question to a
  // real provider gets the bounded general selection instead of a refusal.
  let bundle: RetrievalBundle;
  try {
    bundle = matched ? retrieve(matched.id, REFERENCE_KEY) : retrieveGeneral(REFERENCE_KEY);
  } catch (error) {
    if (error instanceof AnalysisNotAvailable) {
      return base('error', { message: error.message });
    }
    throw error;
  }
  const handlerId = matched?.id ?? GENERAL_HANDLER_ID;

  let provider;
  try {
    provider = createProvider(config);
  } catch (error) {
    return base('misconfigured', {
      handlerId,
      message: error instanceof Error ? error.message : 'The configured provider could not be created.',
    });
  }

  const system: UnitSystem = request?.system === 'imperial' ? 'imperial' : 'metric';
  // Conversation memory: the earlier turns of THIS conversation, bounded here so
  // no caller can send an unbounded history. Empty for a new conversation.
  const history = boundedHistory(request?.history);
  const withContext = {
    handlerId,
    retrieval: retrievalSummary(bundle),
  };

  let answer: AnalystAnswer | null = null;
  let grounding: AnalystGrounding = NO_GROUNDING;

  try {
    const result = await provider.answer({
      refKey: REFERENCE_KEY,
      system,
      bundle,
      question: validated.query,
      prompt: config.systemPrompt,
      notes: notes.text.length > 0 ? notes.text : undefined,
      history,
    });

    if (!result) {
      return base('unsupported', {
        ...withContext,
        message: 'That handler produced no answer from the selected context.',
      });
    }

    if (result.kind === 'answer') {
      // The demo provider computes its answer from the bundle, so there is no
      // model text to audit: the grounding check applies to model replies.
      answer = result.answer;
    } else {
      const parsed = parseAnalystReply(result.text, { bundle });
      if (!parsed.ok || !parsed.answer) {
        return base('error', {
          ...withContext,
          message: parsed.reason ?? "The model's reply could not be read as an answer.",
        });
      }
      answer = parsed.answer;
      grounding = checkGrounding(answer, bundle, system);
    }
  } catch (error) {
    if (error instanceof AnalystProviderError) {
      // The message is already scrubbed by the provider (no key, no credential URL).
      return base('error', { ...withContext, message: error.message });
    }
    throw error;
  }

  return base('ok', {
    ...withContext,
    answer,
    message: null,
    grounding,
  });
}

/** The prompt list a caller may offer, generated from the handler registry. */
export function supportedPrompts(): string[] {
  return SUPPORTED_PROMPTS;
}

/** Metric display names for the selected context, used by the UI panel. */
export function selectedMetricNames(bundle: RetrievalBundle): string[] {
  return [...new Set(bundle.summaries.map(s => getMetric(s.metricId)?.displayName ?? s.metricId))];
}
